### ISSUE TITLE
Cannot recieve any metrics

### ISSUE THREAD

**Issue by nickoffff** [wikimedia/cassandra-metrics-collector#17] opened 2016-07-07 11:34 UTC
I am using Cassandra 3.0 and I have compiled the last cassandra-metrics-collector version from Maven. I added -Dcassandra.instance-id="Node1" to JVM_OPTS in cassandra-env.sh. For testing, I opened a socket as you suggested with "nc -lk 2006". I tried to start the metrics collection both as

`java -jar cassandra-metrics-collector-3.1.3-jar-with-dependencies.jar --interval 60 --carbon-host 127.0.0.1 --carbon-port 2006`

and

```
export CLASSPATH=/usr/share/cassandra/apache-cassandra.jar:/home/boxuser/Downloads/cassandra-metrics-collector-3.1.3-jar-with-dependencies.jar
java org.wikimedia.cassandra.metrics.service.Service --interval 60 --carbon-host 127.0.0.1 --carbon-port 2006
```

I can see the following output in the console:

```
2016-07-07 13:17:19,992 [main] INFO  o.w.c.metrics.service.Service - Starting up...
2016-07-07 13:17:20,096 [main] INFO  org.quartz.impl.StdSchedulerFactory - Using default implementation for ThreadExecutor
2016-07-07 13:17:20,103 [main] INFO  org.quartz.simpl.SimpleThreadPool - Job execution threads will use class loader of thread: main
2016-07-07 13:17:20,117 [main] INFO  o.quartz.core.SchedulerSignalerImpl - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2016-07-07 13:17:20,119 [main] INFO  org.quartz.core.QuartzScheduler - Quartz Scheduler v.2.2.1 created.
2016-07-07 13:17:20,121 [main] INFO  org.quartz.simpl.RAMJobStore - RAMJobStore initialized.
2016-07-07 13:17:20,123 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler meta-data: Quartz Scheduler (v2.2.1) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2016-07-07 13:17:20,123 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2016-07-07 13:17:20,125 [main] INFO  org.quartz.impl.StdSchedulerFactory - Quartz scheduler version: 2.2.1
2016-07-07 13:17:20,147 [main] INFO  org.quartz.core.QuartzScheduler - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2016-07-07 13:17:20,152 [DefaultQuartzScheduler_Worker-1] INFO  o.w.c.metrics.service.Discover - Initiating new discovery cycle
2016-07-07 13:17:20,250 [DefaultQuartzScheduler_Worker-2] INFO  o.w.c.metrics.service.StatsReporter - Writing internal stats
2016-07-07 13:17:30,133 [DefaultQuartzScheduler_Worker-3] INFO  o.w.c.metrics.service.StatsReporter - Writing internal stats
```

But no metrics are reported to the previously opened socket.

**Comment by eevans** [comment] 2016-07-15 17:05
This mode of startup is meant to support auto-discovery/auto configuration.  We use it at the WMF where we run multiple instances of Cassandra on the same host.  Unfortunately, it requires a JVM feature that has since been disabled in Cassandra (starting with version 2.2).

So, you have two options:

1. You can comment out the line in `cassandra-env.sh` that looks like the following:
    ```
    JVM_OPTS="$JVM_OPTS -XX:+PerfDisableSharedMem"
    ```
2. If you don't need the auto-discovery/auto-configuration, you can use the [simple invocation](https://github.com/wikimedia/cassandra-metrics-collector#simple-invocation).

The `-XX:+PerfDisableSharedMem` argument is a good optimization to have (it prevents GC pauses  caused by blocked IO on the `hsperfdata` files, so if you can, I'd stick with the second option.

FWIW, There are plans to revamp the auto-discovery in the near future so that we can have our cake, and eat it too.

Does this help?

**Comment by nickoffff** [comment] 2016-07-18 12:35
I tried your suggestion with the simple invokation. It works but then some wrapper arround it is required to call it repeatedly. It would be nice to habe an interval option too.

**Comment by eevans** [comment] 2016-07-18 15:50
> I tried your suggestion with the simple invokation. It works but then some wrapper or cron arround it is required to call it repeatedly. It would be nice to have an interval option too.

Yeah, this is inconvenient, sorry.  Soon (in the coming weeks, hopefully), there are plans to refactor to use YAML files to discover/configure the instances to collect (including the prefix).

> If the library reads metrics via JMX, why it needs apache-cassandra.jar to be on classpath?

JMX uses [RMI](https://en.wikipedia.org/wiki/Java_remote_method_invocation), which serializes objects on one end, and reconstitutes them on the other (requiring the corresponding class). It used to be enough to depend upon the codahale metrics library, but since Cassandra 2.2, these have been wrapped in Cassandra classes.  Specifically, `o.a.c.metrics.CassandraMetricsRegistry`, (which in turn pulls in quite a few transitive dependencies).

**Comment by nickoffff** [comment] 2016-07-19 05:59
Thank you for the explanation. It would be also great to have configure possibilities, which metrics should be reported, e.g., in the form of wildcards.

**Comment by eevans** [comment] 2016-07-19 16:04
> Thank you for the explanation. It would be also great to have configure possibilities, which metrics should be reported, e.g., in the form of wildcards.

Are you aware of the `-f`/`--filter-config` argument?  With it, you can supply a yaml file containing {white,black}list information ([sample here](https://github.com/wikimedia/cassandra-metrics-collector/blob/master/filter-sample.yaml)).  It is only available when running as a service (it's not available for the simple invocation), but that would be pretty easy to fix.

**Comment by nickoffff** [comment] 2016-07-20 05:49
Yes, but I cannot use it, since only single invokation is working for me.

**Comment by eevans** [comment] 2016-07-20 15:12
> Yes, but I cannot use it, since only single invokation is working for me.

Sure, fair enough. This should be pretty easy to add; Should be something I can get to in the coming days.

**Comment by eevans** [comment] 2016-07-20 15:13
> Yes, but I cannot use it, since only single invokation is working for me.

@nickoffff Could I get you to open a separate bug report for this?

**Comment by nickoffff** [comment] 2016-07-21 05:54
> @nickoffff Could I get you to open a separate bug report for this?

I created a new issue for this.

**Comment by eevans** [comment] 2016-07-21 14:57
@nickoffff awesome, thanks; I'm going to go ahead and close this one now.

**Closed by eevans** 2016-07-21 14:57 UTC
